_target_: src.models.SwinTransformerModule

model_name: swin_tiny_patch4_window7_224
use_pretrained: true
checkpoint_path: /home/sampath/swin_small_patch4_window7_224_22k.pth
num_classes: 14 # should be 15 for a non-tool class


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4 #3e-4 #1e-3
  eps: 1e-08
  betas: [0.9, 0.95] #[0.9, 0.999]
  weight_decay: 5e-5 #1e-4 #0.01

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  optimizer: ${model.optimizer}
  # initial cycle length in epochs
  T_0: 200
  # multiply cycle length by 2 after each restart
  T_mult: 2
  # minimum LR at the end of each cosine anneal
  eta_min: 1e-8
  # start from the beginning
  last_epoch: -1
